<?php

namespace AppBundle\Repository\Core;

/**
 * EnderecoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnderecoRepository extends EntityRepository{
    
}
