DROP DATABASE IF EXISTS user_database;
CREATE DATABASE user_database; 
USE user_database;
CREATE TABLE `user_database`.`users` ( `nome` VARCHAR(255) NOT NULL , `email` VARCHAR(255) NOT NULL , `senha` VARCHAR(20) NOT NULL , `telefone` VARCHAR(20) NOT NULL , `cpf` VARCHAR(20) NOT NULL , `nascimento` VARCHAR(10) NOT NULL , `cep` VARCHAR(10) NOT NULL , `estado` VARCHAR(20) NOT NULL , `logradouro` VARCHAR(255) NOT NULL , `numero` VARCHAR(20) NOT NULL , `complemento` VARCHAR(255) NOT NULL , `cidade` VARCHAR(20) NOT NULL , `bairro` VARCHAR(20) NOT NULL , `rg` VARCHAR(20) NOT NULL , `data_expedicao` VARCHAR(10) NOT NULL , `orgao` VARCHAR(20) NOT NULL , `estado_civil` VARCHAR(10) NOT NULL , `categoria` VARCHAR(10) NOT NULL , `empresa` VARCHAR(30) NOT NULL , `profissao` VARCHAR(30) NOT NULL , `renda` VARCHAR(20) NOT NULL , PRIMARY KEY (`cpf`)) ENGINE = InnoDB;
ALTER TABLE `users` ADD UNIQUE(`cpf`);
CREATE USER 'paulo'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON *.* TO 'paulo'@'localhost' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
